{% set name = "papermill_report" %}
{% set version = "2.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 97780d215c940c74f9143f57039f87dda85b4b7dd39bd24507461e937aa44c22

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - jinja2
    - nbconvert
    - papermill >=2.2.0
    - tornado >=6
    - traitlets >=4

test:
  imports:
    - papermill_report
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
    - python -m papermill_report --help

about:
  home: https://github.com/ariadnext/papermill_report
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Microservice to generate Jupyter reports
  description: |
    Microservice to generate Jupyter reports by executing notebook and exporting them to static HTML page combining [papermill](https://papermill.readthedocs.io/en/latest/) and [nbconvert](nbconvert.readthedocs.io/).

    It can be run as a standalone application or as a JupyterHub service.

extra:
  recipe-maintainers:
    - fcollonval
